// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValetAPI.Data;

#nullable disable

namespace ValetAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221101100534_Add size to Area")]
    partial class AddsizetoArea
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ValetAPI.Models.AreaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Main Dining Area",
                            Height = 10,
                            Name = "Main",
                            VenueId = 1,
                            Width = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Outside Dining Area",
                            Height = 10,
                            Name = "Outside",
                            VenueId = 1,
                            Width = 10
                        },
                        new
                        {
                            Id = 3,
                            Description = "Balcony Dining Area",
                            Height = 10,
                            Name = "Balcony",
                            VenueId = 1,
                            Width = 10
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.AreaSittingEntity", b =>
                {
                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("SittingId")
                        .HasColumnType("int");

                    b.HasKey("AreaId", "SittingId");

                    b.HasIndex("SittingId");

                    b.ToTable("AreaSittings");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            SittingId = 11
                        },
                        new
                        {
                            AreaId = 1,
                            SittingId = 12
                        },
                        new
                        {
                            AreaId = 1,
                            SittingId = 13
                        },
                        new
                        {
                            AreaId = 2,
                            SittingId = 21
                        },
                        new
                        {
                            AreaId = 2,
                            SittingId = 22
                        },
                        new
                        {
                            AreaId = 2,
                            SittingId = 23
                        },
                        new
                        {
                            AreaId = 3,
                            SittingId = 31
                        },
                        new
                        {
                            AreaId = 3,
                            SittingId = 32
                        },
                        new
                        {
                            AreaId = 3,
                            SittingId = 33
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.wick@gmail.com",
                            FirstName = "John",
                            LastName = "Wick",
                            Phone = "0411111111"
                        },
                        new
                        {
                            Id = 2,
                            Email = "keith.smith@gmail.com",
                            FirstName = "Keith",
                            LastName = "Smith",
                            Phone = "0411111112"
                        },
                        new
                        {
                            Id = 3,
                            Email = "penny.wayne@gmail.com",
                            FirstName = "Penny",
                            LastName = "Wayne",
                            Phone = "0411111113"
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.ReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("NoGuests")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SittingId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SittingId");

                    b.HasIndex("VenueId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ValetAPI.Models.SittingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Sittings");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 1, 30, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 24, 23, 30, 0, 0, DateTimeKind.Utc),
                            Type = "Breakfast",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 5, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 25, 2, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Lunch",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 25, 6, 30, 0, 0, DateTimeKind.Utc),
                            Type = "Dinner",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 1, 30, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 24, 23, 30, 0, 0, DateTimeKind.Utc),
                            Type = "Breakfast",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 5, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 25, 2, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Lunch",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 25, 6, 30, 0, 0, DateTimeKind.Utc),
                            Type = "Dinner",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 1, 30, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 24, 23, 30, 0, 0, DateTimeKind.Utc),
                            Type = "Breakfast",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 5, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 25, 2, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Lunch",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 33,
                            Capacity = 50,
                            EndTime = new DateTime(2022, 12, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2022, 12, 25, 6, 30, 0, 0, DateTimeKind.Utc),
                            Type = "Dinner",
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.SittingTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SittingTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 1,
                            Type = "Lunch"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Dinner"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Special"
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.SourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Source = "Website"
                        },
                        new
                        {
                            Id = 1,
                            Source = "InPerson"
                        },
                        new
                        {
                            Id = 2,
                            Source = "Email"
                        },
                        new
                        {
                            Id = 3,
                            Source = "Phone"
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.StateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            State = "Pending"
                        },
                        new
                        {
                            Id = 1,
                            State = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            State = "Cancelled"
                        },
                        new
                        {
                            Id = 3,
                            State = "Assigned"
                        },
                        new
                        {
                            Id = 4,
                            State = "Seated"
                        },
                        new
                        {
                            Id = 5,
                            State = "Completed"
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.TableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            AreaId = 1,
                            Capacity = 1,
                            Type = "M1",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 21,
                            AreaId = 2,
                            Capacity = 1,
                            Type = "O1",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 31,
                            AreaId = 3,
                            Capacity = 1,
                            Type = "B1",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 12,
                            AreaId = 1,
                            Capacity = 2,
                            Type = "M2",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 22,
                            AreaId = 2,
                            Capacity = 2,
                            Type = "O2",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 32,
                            AreaId = 3,
                            Capacity = 2,
                            Type = "B2",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 13,
                            AreaId = 1,
                            Capacity = 3,
                            Type = "M3",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 23,
                            AreaId = 2,
                            Capacity = 3,
                            Type = "O3",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 33,
                            AreaId = 3,
                            Capacity = 3,
                            Type = "B3",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 14,
                            AreaId = 1,
                            Capacity = 4,
                            Type = "M4",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 24,
                            AreaId = 2,
                            Capacity = 4,
                            Type = "O4",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 34,
                            AreaId = 3,
                            Capacity = 4,
                            Type = "B4",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 15,
                            AreaId = 1,
                            Capacity = 5,
                            Type = "M5",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 25,
                            AreaId = 2,
                            Capacity = 5,
                            Type = "O5",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 35,
                            AreaId = 3,
                            Capacity = 5,
                            Type = "B5",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 16,
                            AreaId = 1,
                            Capacity = 6,
                            Type = "M6",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 26,
                            AreaId = 2,
                            Capacity = 6,
                            Type = "O6",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 36,
                            AreaId = 3,
                            Capacity = 6,
                            Type = "B6",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 17,
                            AreaId = 1,
                            Capacity = 7,
                            Type = "M7",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 27,
                            AreaId = 2,
                            Capacity = 7,
                            Type = "O7",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 37,
                            AreaId = 3,
                            Capacity = 7,
                            Type = "B7",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 18,
                            AreaId = 1,
                            Capacity = 8,
                            Type = "M8",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 28,
                            AreaId = 2,
                            Capacity = 8,
                            Type = "O8",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 38,
                            AreaId = 3,
                            Capacity = 8,
                            Type = "B8",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 19,
                            AreaId = 1,
                            Capacity = 9,
                            Type = "M9",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 29,
                            AreaId = 2,
                            Capacity = 9,
                            Type = "O9",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 39,
                            AreaId = 3,
                            Capacity = 9,
                            Type = "B9",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 20,
                            AreaId = 1,
                            Capacity = 10,
                            Type = "M10",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 30,
                            AreaId = 2,
                            Capacity = 10,
                            Type = "O10",
                            VenueId = 0
                        },
                        new
                        {
                            Id = 40,
                            AreaId = 3,
                            Capacity = 10,
                            Type = "B10",
                            VenueId = 0
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.VenueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 George St",
                            Name = "Saki"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ValetAPI.Models.AreaEntity", b =>
                {
                    b.HasOne("ValetAPI.Models.VenueEntity", "Venue")
                        .WithMany("Areas")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ValetAPI.Models.AreaSittingEntity", b =>
                {
                    b.HasOne("ValetAPI.Models.AreaEntity", "Area")
                        .WithMany("AreaSittings")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.SittingEntity", "Sitting")
                        .WithMany("AreaSittings")
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("ValetAPI.Models.ReservationEntity", b =>
                {
                    b.HasOne("ValetAPI.Models.AreaEntity", "Area")
                        .WithMany("Reservations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.CustomerEntity", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.SittingEntity", "Sitting")
                        .WithMany("Reservations")
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.VenueEntity", "Venue")
                        .WithMany("Reservations")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Customer");

                    b.Navigation("Sitting");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ValetAPI.Models.SittingEntity", b =>
                {
                    b.HasOne("ValetAPI.Models.VenueEntity", "Venue")
                        .WithMany("Sittings")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ValetAPI.Models.TableEntity", b =>
                {
                    b.HasOne("ValetAPI.Models.AreaEntity", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.ReservationEntity", "Reservation")
                        .WithMany("Tables")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Area");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ValetAPI.Models.AreaEntity", b =>
                {
                    b.Navigation("AreaSittings");

                    b.Navigation("Reservations");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("ValetAPI.Models.CustomerEntity", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ValetAPI.Models.ReservationEntity", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("ValetAPI.Models.SittingEntity", b =>
                {
                    b.Navigation("AreaSittings");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ValetAPI.Models.VenueEntity", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Reservations");

                    b.Navigation("Sittings");
                });
#pragma warning restore 612, 618
        }
    }
}
