// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValetAPI.Data;

#nullable disable

namespace ValetAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220901030358_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ValetAPI.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gorgeous Main Dining Area",
                            Name = "Main Dining",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Outside with a view",
                            Name = "Outside",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Upstairs away from the noise",
                            Name = "Upstairs",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gorgeous Main Dining Area",
                            Name = "Main Dining",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Outside with a view",
                            Name = "Outside",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Upstairs away from the noise",
                            Name = "Upstairs",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Gorgeous Main Dining Area",
                            Name = "Main Dining",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 8,
                            Description = "Outside with a view",
                            Name = "Outside",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Upstairs away from the noise",
                            Name = "Upstairs",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Gorgeous Main Dining Area",
                            Name = "Main Dining",
                            VenueId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Outside with a view",
                            Name = "Outside",
                            VenueId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Upstairs away from the noise",
                            Name = "Upstairs",
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ValetAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("NoGuests")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SittingId")
                        .HasColumnType("int");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SittingId");

                    b.HasIndex("VenueId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ValetAPI.Models.Sitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("VenueId");

                    b.ToTable("Sittings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            EndTime = new DateTime(2022, 12, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            EndTime = new DateTime(2022, 12, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Lunch"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            EndTime = new DateTime(2022, 12, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Dinner"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            EndTime = new DateTime(2022, 12, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 2,
                            EndTime = new DateTime(2022, 12, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Lunch"
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 2,
                            EndTime = new DateTime(2022, 12, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Dinner"
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 3,
                            EndTime = new DateTime(2022, 12, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 8,
                            AreaId = 3,
                            EndTime = new DateTime(2022, 12, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Lunch"
                        },
                        new
                        {
                            Id = 9,
                            AreaId = 3,
                            EndTime = new DateTime(2022, 12, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Dinner"
                        },
                        new
                        {
                            Id = 10,
                            AreaId = 4,
                            EndTime = new DateTime(2022, 12, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Breakfast"
                        },
                        new
                        {
                            Id = 11,
                            AreaId = 4,
                            EndTime = new DateTime(2022, 12, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Lunch"
                        },
                        new
                        {
                            Id = 12,
                            AreaId = 4,
                            EndTime = new DateTime(2022, 12, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2022, 12, 25, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = "Dinner"
                        });
                });

            modelBuilder.Entity("ValetAPI.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("ValetAPI.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 George St",
                            Name = "KFC"
                        },
                        new
                        {
                            Id = 2,
                            Address = "321 Frank St",
                            Name = "Maccas"
                        },
                        new
                        {
                            Id = 3,
                            Address = "999 Kent St",
                            Name = "Red Rooster"
                        },
                        new
                        {
                            Id = 4,
                            Address = "555 Parade Dr",
                            Name = "Guzman Y Gomez"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ValetAPI.Models.Area", b =>
                {
                    b.HasOne("ValetAPI.Models.Venue", "Venue")
                        .WithMany("Areas")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ValetAPI.Models.Reservation", b =>
                {
                    b.HasOne("ValetAPI.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.Sitting", "Sitting")
                        .WithMany("Reservations")
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.Venue", null)
                        .WithMany("Reservations")
                        .HasForeignKey("VenueId");

                    b.Navigation("Customer");

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("ValetAPI.Models.Sitting", b =>
                {
                    b.HasOne("ValetAPI.Models.Area", "Area")
                        .WithMany("Sessions")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.Venue", null)
                        .WithMany("Sittings")
                        .HasForeignKey("VenueId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ValetAPI.Models.Table", b =>
                {
                    b.HasOne("ValetAPI.Models.Area", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValetAPI.Models.Reservation", null)
                        .WithMany("Tables")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ValetAPI.Models.Area", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("ValetAPI.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ValetAPI.Models.Reservation", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("ValetAPI.Models.Sitting", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ValetAPI.Models.Venue", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Reservations");

                    b.Navigation("Sittings");
                });
#pragma warning restore 612, 618
        }
    }
}
